-- Create fqdns table
-- FQDNテーブルを作成します

CREATE TABLE fqdns (
  id CHAR(36) PRIMARY KEY COMMENT 'FQDN ID (UUID)',
  fqdn VARCHAR(255) NOT NULL UNIQUE COMMENT 'FQDN',
  description VARCHAR(500) NULL COMMENT '説明',
  status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE' COMMENT 'ステータス',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  INDEX idx_fqdns_fqdn (fqdn),
  INDEX idx_fqdns_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='FQDNテーブル';
